spring:
  datasource:
    url: jdbc:mysql://localhost:3306/donjodb?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    defer-datasource-initialization: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

logging.level:
  org.hibernate.SQL: error
# org.hibernate.type: trace

# swagger setting
springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: false


jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'ssafy-8th-generation-class-2-team-9-jaewook-hyunju-hyunsu-taehyun-taesun-yuyoung-project-fighting-jwt-secret-secret-jwt-token'|base64
  secret: c3NhZnk4dGgtOGdlbmVyYXRpb24tY2xhc3MtdGVhbS05LWphZXdvb2stcnVubnktcnVubnktdGFlc3QtdGFlc3VuLXl1eW9uZy1wcm9qZWN0LWZpZ2h0aW5nLWp3dC1zZWNyZXQtc2VjcmV0LXNlY3JldC1qd3QtdG9rZW4=
  token-validity-in-minutes: 30

# loggin level
logging:
  level:
    root: info  # TRACE  <  DEBUG  <  INFO  <  WARN  <  ERROR



# s3
cloud:
  aws:
    s3:
      bucket: don-jo
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: AKIAREBD2QI77A32LV6T
      secretKey: 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

# eth address
eth:
  address: '0x288fB136C9291a4b62f1620bEE5901BEB2B0ffD7'
  privateKey: '9c63b31a88c410c7d33265876407b31aea175c589ec82fff8d0bc4aa2baf150d'
  rpcUtil : 'https://sepolia.infura.io/v3/ac3a17c914fd47a29cb5ed54315f746a'
  applicationAddress : '0xdBEeDa3fB7d11CC14638A8994b16db785Db0B7d8'
#  rpcUtil: 'http://j8a209.p.ssaft.io:8545'
#  applicationAddress: '0xBf431108276e429c168E12938E8f1BF823Ee02B6'

